import type { Niche } from "./types";

export const NICHES: Niche[] = [
  {
    id: "tow",
    name: "Tow / roadside",
    slug: "tow",
    jobValue: 280,
    jobRange: "$150–$450",
    closeRate: 0.5,
    typicalMonthlyLeads: 35,
    urgency: "emergency",
    gbpPrimary: "Towing service",
    gbpSecondary: ["Roadside assistance service", "Motorcycle towing service"],
    services: ["Light-duty towing", "Jump starts", "Lockouts", "Tire changes", "Winch-outs", "Accident recovery"],
    hours: "24/7",
  },
  {
    id: "dental",
    name: "Emergency / mobile dental",
    slug: "emergencydental",
    jobValue: 650,
    jobRange: "$250–$8,000",
    closeRate: 0.3,
    typicalMonthlyLeads: 18,
    urgency: "emergency",
    gbpPrimary: "Emergency dental service",
    gbpSecondary: ["Dentist", "Dental clinic", "Cosmetic dentist"],
    services: ["Same-day emergency exams", "Toothache / extraction", "Broken tooth repair", "Implant consults", "Mobile visits for homebound patients"],
    hours: "7 days, emergency line 24/7",
  },
  {
    id: "dryer",
    name: "Dryer vent cleaning",
    slug: "dryervent",
    jobValue: 189,
    jobRange: "$149–$249",
    closeRate: 0.45,
    typicalMonthlyLeads: 28,
    urgency: "scheduled",
    gbpPrimary: "Dryer vent cleaning service",
    gbpSecondary: ["Duct cleaning service", "Home cleaning service"],
    services: ["Dryer vent cleaning", "Roof cap replacement", "Lint fire inspection", "Long-run vent installs"],
    hours: "Mon–Sat 8a–6p, emergency same-day",
  },
  {
    id: "crawl",
    name: "Crawl space / mold",
    slug: "crawlspace",
    jobValue: 2200,
    jobRange: "$1,200–$4,500",
    closeRate: 0.25,
    typicalMonthlyLeads: 12,
    urgency: "mixed",
    gbpPrimary: "Crawl space cleaning service",
    gbpSecondary: ["Mold remediation service", "Waterproofing service"],
    services: ["Crawl space cleanup", "Encapsulation", "Vapor barrier", "Dehumidifier install", "Mold inspection"],
    hours: "Mon–Fri 7a–6p, Sat 8a–2p",
  },
  {
    id: "septic",
    name: "Septic",
    slug: "septic",
    jobValue: 550,
    jobRange: "$350–$1,200",
    closeRate: 0.4,
    typicalMonthlyLeads: 18,
    urgency: "mixed",
    gbpPrimary: "Septic system service",
    gbpSecondary: ["Septic tank pumping service", "Plumbing service"],
    services: ["Septic pumping", "Inspections", "Baffle repair", "Emergency backups", "Lid locate"],
    hours: "Mon–Sat 7a–7p, emergency 24/7",
  },
  {
    id: "gutter",
    name: "Gutter cleaning",
    slug: "gutters",
    jobValue: 260,
    jobRange: "$180–$450",
    closeRate: 0.4,
    typicalMonthlyLeads: 22,
    urgency: "scheduled",
    gbpPrimary: "Gutter cleaning service",
    gbpSecondary: ["Gutter repair service", "Roofing contractor"],
    services: ["Gutter cleaning", "Downspout flush", "Gutter guard install", "Minor repair"],
    hours: "Mon–Sat 8a–6p",
  },
  {
    id: "handyman",
    name: "Handyman",
    slug: "handyman",
    jobValue: 220,
    jobRange: "$150–$400",
    closeRate: 0.35,
    typicalMonthlyLeads: 30,
    urgency: "scheduled",
    gbpPrimary: "Handyman",
    gbpSecondary: ["Home improvement service", "Carpenter"],
    services: ["Repairs", "Installs", "Drywall", "Doors and locks", "TV mounting"],
    hours: "Mon–Sat 8a–6p",
  },
  {
    id: "appliance",
    name: "Appliance repair",
    slug: "appliancerepair",
    jobValue: 210,
    jobRange: "$120–$350",
    closeRate: 0.45,
    typicalMonthlyLeads: 26,
    urgency: "mixed",
    gbpPrimary: "Appliance repair service",
    gbpSecondary: ["Refrigerator repair service", "Washer & dryer repair service"],
    services: ["Refrigerator", "Washer / dryer", "Dishwasher", "Oven / range", "In-home diagnosis"],
    hours: "Mon–Sat 8a–7p, same-day windows",
  },
  {
    id: "mechanic",
    name: "Mobile mechanic",
    slug: "mobilemechanic",
    jobValue: 280,
    jobRange: "$180–$500",
    closeRate: 0.4,
    typicalMonthlyLeads: 24,
    urgency: "mixed",
    gbpPrimary: "Mobile mechanic",
    gbpSecondary: ["Auto repair shop", "Oil change service"],
    services: ["On-site diagnostics", "Battery", "Brakes", "Oil", "No-start recovery"],
    hours: "Mon–Sat 7a–7p, emergency after-hours",
  },
  {
    id: "ev",
    name: "EV charger installation",
    slug: "evcharger",
    jobValue: 1400,
    jobRange: "$800–$2,500",
    closeRate: 0.2,
    typicalMonthlyLeads: 10,
    urgency: "scheduled",
    gbpPrimary: "Electric vehicle charging station",
    gbpSecondary: ["Electrician", "Electrical installation service"],
    services: ["Level 2 home charger install", "Panel check", "Permit handling", "Tesla / universal setups"],
    hours: "Mon–Fri 8a–5p",
  },
  {
    id: "generator",
    name: "Standby generator",
    slug: "generator",
    jobValue: 14500,
    jobRange: "$9,500–$30,000",
    closeRate: 0.18,
    typicalMonthlyLeads: 10,
    urgency: "mixed",
    gbpPrimary: "Generator installation service",
    gbpSecondary: ["Electrician", "Generator repair service"],
    services: ["Whole-home standby install", "Transfer switch", "Portable inlet", "Load calc", "Storm-prep service"],
    hours: "Mon–Sat 7a–6p, storm days 24/7",
  },
  {
    id: "garage",
    name: "Garage door",
    slug: "garagedoor",
    jobValue: 420,
    jobRange: "$250–$5,000",
    closeRate: 0.4,
    typicalMonthlyLeads: 22,
    urgency: "mixed",
    gbpPrimary: "Garage door supplier",
    gbpSecondary: ["Garage door repair service", "Gate installation service"],
    services: ["Spring / cable repair", "Hurricane-rated doors", "Opener replace", "Salt-air hardware"],
    hours: "Mon–Sat 8a–6p, emergency spring 7 days",
  },
  {
    id: "well",
    name: "Well pump",
    slug: "wellpump",
    jobValue: 1400,
    jobRange: "$800–$3,500",
    closeRate: 0.4,
    typicalMonthlyLeads: 12,
    urgency: "emergency",
    gbpPrimary: "Water well drilling service",
    gbpSecondary: ["Pump service", "Plumbing service"],
    services: ["Pump replace", "Pressure tank", "No-water emergency", "New well", "Water test"],
    hours: "Mon–Sat 7a–7p, no-water 24/7",
  },
  {
    id: "tree",
    name: "Storm / tree",
    slug: "treeservice",
    jobValue: 1800,
    jobRange: "$450–$6,000",
    closeRate: 0.35,
    typicalMonthlyLeads: 16,
    urgency: "emergency",
    gbpPrimary: "Tree service",
    gbpSecondary: ["Emergency tree removal service", "Stump grinding service"],
    services: ["Storm take-down", "Hanger removal", "Stump grind", "Lot clearing", "Crane jobs"],
    hours: "Storm days 24/7, else Mon–Sat 7a–6p",
  },
  {
    id: "water",
    name: "Water damage",
    slug: "waterdamage",
    jobValue: 4200,
    jobRange: "$1,200–$12,000",
    closeRate: 0.28,
    typicalMonthlyLeads: 14,
    urgency: "emergency",
    gbpPrimary: "Water damage restoration service",
    gbpSecondary: ["Flood restoration service", "Mold remediation service"],
    services: ["Extract", "Dry-out", "Flood cut", "Pack-out", "Insurance walk-through"],
    hours: "24/7 water-in-house",
  },
  {
    id: "mosquito",
    name: "Mosquito / barrier",
    slug: "mosquitocontrol",
    jobValue: 189,
    jobRange: "$79–$350",
    closeRate: 0.45,
    typicalMonthlyLeads: 32,
    urgency: "scheduled",
    gbpPrimary: "Pest control service",
    gbpSecondary: ["Mosquito control service", "Wildlife control service"],
    services: ["Barrier spray", "Yard fog", "Standing water treat", "Seasonal plan", "Event spray"],
    hours: "Mon–Sat 8a–6p, dusk windows",
  },
  {
    id: "pool",
    name: "Pool service",
    slug: "poolservice",
    jobValue: 220,
    jobRange: "$140–$2,800",
    closeRate: 0.4,
    typicalMonthlyLeads: 24,
    urgency: "scheduled",
    gbpPrimary: "Swimming pool cleaning service",
    gbpSecondary: ["Swimming pool repair service", "Hot tub repair service"],
    services: ["Weekly route", "Green-to-clean", "Pump / filter", "Salt cell", "Open / close"],
    hours: "Mon–Sat 8a–5p",
  },
  {
    id: "dock",
    name: "Dock / boat lift",
    slug: "dockrepair",
    jobValue: 3200,
    jobRange: "$800–$14,000",
    closeRate: 0.3,
    typicalMonthlyLeads: 10,
    urgency: "mixed",
    gbpPrimary: "Dock builder",
    gbpSecondary: ["Boat lift repair service", "Marine contractor"],
    services: ["Dock repair", "Boat lift", "Pilings", "Storm re-set", "Flotation"],
    hours: "Mon–Sat 7a–6p, storm follow-up 7 days",
  },
];

export function nicheById(id: string) {
  const niche = NICHES.find((n) => n.id === id);
  if (!niche) throw new Error(`Unknown niche ${id}`);
  return niche;
}

export function nicheLabel(id: string) {
  return NICHES.find((n) => n.id === id)?.name ?? id;
}
