import { inferCountyFromHood } from "./territory";
import { monthlySeat, pplPrice } from "./pricing";
import { nicheById } from "./niches";
import { HUNT, SEAT_NICHES, marketIdForNiche } from "./seats";
import { domainFor } from "./utils";
import { FREE_TRIAL } from "./types";
import type { Buyer, CallTurn, County, HuntStatus, Lead, Market } from "./types";

const NOW = Date.parse("2026-09-02T15:18:00.000Z");

function ago(hours: number) {
  return new Date(NOW - hours * 3_600_000).toISOString();
}

function turns(rows: [string, CallTurn["speaker"], string][]): CallTurn[] {
  return rows.map(([at, speaker, text]) => ({ at, speaker, text }));
}

function m(
  partial: Omit<Market, "pplPrice" | "leadsThisMonth" | "soldThisMonth" | "revenueThisMonth" | "state"> & {
    pplPrice?: number;
    leadsThisMonth?: number;
    soldThisMonth?: number;
    revenueThisMonth?: number;
    state?: string;
  },
): Market {
  const niche = nicheById(partial.nicheId);
  return {
    pplPrice: partial.pplPrice ?? pplPrice(niche),
    leadsThisMonth: partial.leadsThisMonth ?? 0,
    soldThisMonth: partial.soldThisMonth ?? 0,
    revenueThisMonth: partial.revenueThisMonth ?? 0,
    state: "NC",
    ...partial,
  };
}

const ALAMO_NOTES: Record<string, string> = {
  septic: "Comal/Guadalupe septic belt. Unincorporated Bexar. Do not rank downtown SAWS sewer.",
  generator: "ERCOT ice + Hill Country outages. Don't fight SA electrician LSA.",
  dryer: "North Bexar / New Braunfels volume. Not the hero ticket.",
  well: "Comal hill wells. Mills ignore. Strongest rural TX seat.",
  garage: "Fight storm doors only. Overhead Door owns generic SA.",
  tree: "Storm take-downs + oak wilt language. Angi lists it, nobody owns emergency.",
  water: "Steal SERVPRO overflow. Don't pretend you're the franchise.",
  mosquito: "Recurring barrier. Franchises run ads, don't own the county page.",
  pool: "Strongest TX volume. Stone Oak / New Braunfels / Cibolo weekly.",
  dock: "Canyon Lake + McQueeney lifts. Not the River Walk. Thinnest SERP.",
};

const ALAMO_MARKETS: Market[] = SEAT_NICHES.map((id, i) => {
  const niche = nicheById(id);
  return m({
    id: `alamo-${id}`,
    city: "New Braunfels",
    state: "TX",
    nicheId: id,
    counties: ["bexar", "comal", "guadalupe"],
    neighborhoods: ["New Braunfels", "Canyon Lake", "Schertz", "Cibolo", "Stone Oak", "Helotes", "Seguin"],
    population: 2400000,
    domain: domainFor("alamo", niche.slug),
    trackingNumber: `(210) 555-01${String(i).padStart(2, "0")}`,
    score: {
      demand: 8,
      jobValue: niche.jobValue >= 1000 ? 9 : 7,
      weakCompetitors: 8,
      willingness: 8,
      ease: 8,
      notes: ALAMO_NOTES[id],
    },
    stage: id === "septic" || id === "pool" || id === "well" || id === "dock" ? "build" : "score",
    callsThisMonth: 0,
    jobsEstimated: 0,
    rankMaps: null,
    rankOrganic: null,
    aiCitations: null,
    topQueries: [`${niche.name.toLowerCase()} New Braunfels`, `${niche.name.toLowerCase()} Schertz TX`],
    createdAt: "2026-09-02",
  });
});

export const SEED_MARKETS: Market[] = [
  m({
    id: "wilmington-septic",
    city: "Wilmington",
    nicheId: "septic",
    counties: ["new-hanover", "pender", "brunswick"],
    neighborhoods: ["Leland", "Hampstead", "Porters Neck", "Carolina Beach", "Southport"],
    population: 493000,
    domain: "wilmingtonseptic.com",
    trackingNumber: "(910) 555-0144",
    score: {
      demand: 9,
      jobValue: 8,
      weakCompetitors: 8,
      willingness: 9,
      ease: 8,
      notes: "Tri-county septic. Brunswick sewer lag. Family pumpers, brochure sites.",
    },
    stage: "live",
    callsThisMonth: 41,
    jobsEstimated: 14,
    rankMaps: 2,
    rankOrganic: 1,
    aiCitations: 2,
    topQueries: ["septic pumping Wilmington NC", "septic backup Leland", "septic inspection Pender"],
    createdAt: "2026-07-12",
    siteLiveAt: "2026-07-28",
  }),
  m({
    id: "wilmington-generator",
    city: "Wilmington",
    nicheId: "generator",
    counties: ["new-hanover", "brunswick", "pender"],
    neighborhoods: ["Landfall", "St. James", "Leland", "Wrightsville", "Hampstead"],
    population: 493000,
    domain: "capefeargenerator.com",
    trackingNumber: "(910) 555-0172",
    score: {
      demand: 8,
      jobValue: 10,
      weakCompetitors: 7,
      willingness: 8,
      ease: 7,
      notes: "Florence memory. $12–20k tickets. We answer, then hand a screened job.",
    },
    stage: "live",
    callsThisMonth: 19,
    jobsEstimated: 3,
    rankMaps: 3,
    rankOrganic: 2,
    aiCitations: 1,
    topQueries: ["whole house generator Wilmington", "Generac install Leland"],
    createdAt: "2026-07-20",
    siteLiveAt: "2026-08-04",
  }),
  m({
    id: "wilmington-dryer",
    city: "Wilmington",
    nicheId: "dryer",
    counties: ["new-hanover", "brunswick"],
    neighborhoods: ["Myrtle Grove", "Leland", "Porters Neck", "Carolina Beach"],
    population: 493000,
    domain: "wilmingtondryervent.com",
    trackingNumber: "(910) 555-0118",
    score: {
      demand: 8,
      jobValue: 6,
      weakCompetitors: 9,
      willingness: 8,
      ease: 9,
      notes: "Humidity + long vents. Thin SERP. Season is open.",
    },
    stage: "live",
    callsThisMonth: 22,
    jobsEstimated: 8,
    rankMaps: 2,
    rankOrganic: 1,
    aiCitations: 1,
    topQueries: ["dryer vent cleaning Wilmington", "dryer vent fire Leland"],
    createdAt: "2026-08-04",
    siteLiveAt: "2026-08-12",
  }),
  m({
    id: "wilmington-garage",
    city: "Wilmington",
    nicheId: "garage",
    counties: ["new-hanover", "brunswick"],
    neighborhoods: ["Myrtle Grove", "Porters Neck", "Leland", "Carolina Beach"],
    population: 493000,
    domain: "wilmingtongaragedoor.com",
    trackingNumber: "(910) 555-0190",
    score: {
      demand: 7,
      jobValue: 7,
      weakCompetitors: 7,
      willingness: 7,
      ease: 8,
      notes: "Salt eats springs. Hurricane-rated doors after named storms.",
    },
    stage: "ranking",
    callsThisMonth: 6,
    jobsEstimated: 1,
    rankMaps: 6,
    rankOrganic: 4,
    aiCitations: 0,
    topQueries: ["garage door repair Wilmington NC", "hurricane garage door Leland"],
    createdAt: "2026-08-10",
    siteLiveAt: "2026-08-22",
  }),
  m({
    id: "pender-well",
    city: "Hampstead",
    nicheId: "well",
    counties: ["pender", "brunswick"],
    neighborhoods: ["Hampstead", "Burgaw", "Rocky Point", "Surf City"],
    population: 68000,
    domain: "penderwellpump.com",
    trackingNumber: "(910) 555-0121",
    score: {
      demand: 8,
      jobValue: 8,
      weakCompetitors: 8,
      willingness: 7,
      ease: 8,
      notes: "Pender growth on wells. Same dirt as septic.",
    },
    stage: "build",
    callsThisMonth: 0,
    jobsEstimated: 0,
    rankMaps: null,
    rankOrganic: null,
    aiCitations: null,
    topQueries: ["well pump Hampstead", "no water Pender County"],
    createdAt: "2026-08-28",
  }),
  m({
    id: "brunswick-crawl",
    city: "Leland",
    nicheId: "crawl",
    counties: ["brunswick"],
    neighborhoods: ["Leland", "Bolivia", "Southport", "Oak Island", "St. James"],
    population: 175000,
    domain: "brunswickcrawlspace.com",
    trackingNumber: "(910) 555-0184",
    score: {
      demand: 7,
      jobValue: 9,
      weakCompetitors: 5,
      willingness: 7,
      ease: 6,
      notes: "Brunswick-only. Do not fight Ninja for Wilmington city.",
    },
    stage: "score",
    callsThisMonth: 0,
    jobsEstimated: 0,
    rankMaps: null,
    rankOrganic: null,
    aiCitations: null,
    topQueries: [],
    createdAt: "2026-09-01",
  }),
  m({
    id: "wilmington-tree",
    city: "Wilmington",
    nicheId: "tree",
    counties: ["new-hanover", "pender", "brunswick"],
    neighborhoods: ["Porters Neck", "Hampstead", "Leland", "Myrtle Grove", "Oak Island"],
    population: 493000,
    domain: "capefeartree.com",
    trackingNumber: "(910) 555-0160",
    score: {
      demand: 8,
      jobValue: 8,
      weakCompetitors: 7,
      willingness: 8,
      ease: 8,
      notes: "Storm take-downs. Angi lists it. Nobody owns emergency tree + hanger.",
    },
    stage: "build",
    callsThisMonth: 0,
    jobsEstimated: 0,
    rankMaps: null,
    rankOrganic: null,
    aiCitations: null,
    topQueries: ["emergency tree removal Wilmington", "storm tree Leland"],
    createdAt: "2026-09-02",
  }),
  m({
    id: "wilmington-water",
    city: "Wilmington",
    nicheId: "water",
    counties: ["new-hanover", "pender", "brunswick"],
    neighborhoods: ["Wilmington", "Leland", "Hampstead", "Carolina Beach", "Southport"],
    population: 493000,
    domain: "capefearwaterdamage.com",
    trackingNumber: "(910) 555-0166",
    score: {
      demand: 8,
      jobValue: 9,
      weakCompetitors: 5,
      willingness: 8,
      ease: 6,
      notes: "SERVPRO owns the brand. Independents take overflow. Fight, don't hero.",
    },
    stage: "score",
    callsThisMonth: 0,
    jobsEstimated: 0,
    rankMaps: null,
    rankOrganic: null,
    aiCitations: null,
    topQueries: [],
    createdAt: "2026-09-02",
  }),
  m({
    id: "wilmington-mosquito",
    city: "Wilmington",
    nicheId: "mosquito",
    counties: ["new-hanover", "pender", "brunswick"],
    neighborhoods: ["Wrightsville", "Hampstead", "St. James", "Landfall", "Leland"],
    population: 493000,
    domain: "capefearmosquito.com",
    trackingNumber: "(910) 555-0176",
    score: {
      demand: 9,
      jobValue: 6,
      weakCompetitors: 8,
      willingness: 8,
      ease: 9,
      notes: "Coastal mosquito factory. Recurring barrier. Franchises run ads, don't own the page.",
    },
    stage: "build",
    callsThisMonth: 0,
    jobsEstimated: 0,
    rankMaps: null,
    rankOrganic: null,
    aiCitations: null,
    topQueries: ["mosquito spray Wilmington", "yard mosquito Leland"],
    createdAt: "2026-09-02",
  }),
  m({
    id: "wilmington-pool",
    city: "Wilmington",
    nicheId: "pool",
    counties: ["new-hanover", "brunswick", "pender"],
    neighborhoods: ["Landfall", "Leland", "St. James", "Hampstead", "Porters Neck"],
    population: 493000,
    domain: "capefearpoolservice.com",
    trackingNumber: "(910) 555-0182",
    score: {
      demand: 8,
      jobValue: 6,
      weakCompetitors: 8,
      willingness: 7,
      ease: 8,
      notes: "Weekly routes. Brunswick golf + Landfall. Thin dedicated SERP.",
    },
    stage: "score",
    callsThisMonth: 0,
    jobsEstimated: 0,
    rankMaps: null,
    rankOrganic: null,
    aiCitations: null,
    topQueries: [],
    createdAt: "2026-09-02",
  }),
  m({
    id: "wilmington-dock",
    city: "Wilmington",
    nicheId: "dock",
    counties: ["new-hanover", "brunswick", "pender"],
    neighborhoods: ["Wrightsville", "Surf City", "Southport", "Oak Island", "Figure Eight"],
    population: 493000,
    domain: "capefeardock.com",
    trackingNumber: "(910) 555-0188",
    score: {
      demand: 7,
      jobValue: 9,
      weakCompetitors: 9,
      willingness: 8,
      ease: 8,
      notes: "Best new wedge. Boat lifts. Mills don't list this right.",
    },
    stage: "build",
    callsThisMonth: 0,
    jobsEstimated: 0,
    rankMaps: null,
    rankOrganic: null,
    aiCitations: null,
    topQueries: ["boat lift repair Wrightsville", "dock repair Southport"],
    createdAt: "2026-09-02",
  }),
  ...ALAMO_MARKETS,
];

function buyer(partial: Omit<Buyer, "soldThisMonth" | "spendThisMonth" | "freeRemaining" | "freeUsed"> & {
  soldThisMonth?: number;
  spendThisMonth?: number;
  freeRemaining?: number;
  freeUsed?: number;
}): Buyer {
  const hunt: HuntStatus = partial.hunt;
  const trialOpen = hunt === "trial" || hunt === "pitched" || hunt === "open";
  return {
    soldThisMonth: 0,
    spendThisMonth: 0,
    freeRemaining: hunt === "paying" ? 0 : trialOpen ? FREE_TRIAL : 0,
    freeUsed: hunt === "paying" ? FREE_TRIAL : 0,
    ...partial,
  };
}

function huntStatus(h: HuntStatus): Buyer["status"] {
  if (h === "paying" || h === "trial") return "active";
  return "prospect";
}

export const SEED_BUYERS: Buyer[] = HUNT.map((row) => {
  const niche = nicheById(row.nicheId);
  return buyer({
    id: row.id,
    name: row.name,
    company: row.company,
    phone: row.phone,
    email: row.email,
    marketIds: [marketIdForNiche(row.nicheId, row.county)],
    nicheId: row.nicheId,
    county: row.county,
    pplRate: pplPrice(niche),
    monthlySeat: monthlySeat(niche),
    monthlyCap: 20,
    status: huntStatus(row.hunt),
    hunt: row.hunt,
    notes: row.notes,
    freeRemaining: row.hunt === "paying" ? 0 : FREE_TRIAL,
    freeUsed: row.hunt === "paying" ? FREE_TRIAL : row.id === "by-storm" ? 1 : 0,
  });
});

type LeadSeed = Omit<Lead, "id">;

const LEAD_SEEDS: LeadSeed[] = [
  {
    marketId: "wilmington-septic",
    at: ago(0.15),
    name: "Carla Dyer",
    phone: "(910) 441-2290",
    neighborhood: "Leland",
    zip: "28451",
    county: "brunswick",
    address: "118 Pine Needle Ct, Leland",
    source: "call",
    service: "Emergency backup",
    notes: "Sewage in yard. Two baths down.",
    status: "new",
    screen: "hot",
    urgency: "now",
    screenNotes: "Brunswick. Sewage in yard. Home now. Not a realtor. Wants a truck today.",
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, septic, this is the desk. You're on 910-555-0144."],
      ["0:07", "caller", "This is Carla in Leland. Sewage is in the yard. Both bathrooms are down."],
      ["0:16", "agent", "How long, and can a truck get in?"],
      ["0:20", "caller", "Since this morning. Driveway's clear. I'm home."],
      ["0:26", "agent", "That's a backup, not a routine pump. I'm handing you to a local owner. Stay by this number."],
      ["0:34", "caller", "Please hurry."],
    ]),
  },
  {
    marketId: "wilmington-septic",
    at: ago(0.6),
    name: "Tom Brant",
    phone: "(910) 512-8831",
    neighborhood: "Hampstead",
    zip: "28443",
    county: "pender",
    address: "44 Sloop Point Rd, Hampstead",
    source: "form",
    service: "Pumping + inspection",
    notes: "House closing Friday.",
    status: "new",
    screen: "screening",
    urgency: "week",
    screenNotes: "Pender. Real estate close Friday. Need pump + inspect. Callback done, waiting on lot access.",
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, septic — calling about the form you just sent."],
      ["0:08", "caller", "Yeah, closing Friday in Hampstead. Lender wants a pump and inspect."],
      ["0:18", "agent", "We cover Pender. Who's the listing agent, and is the lid already marked?"],
      ["0:24", "caller", "Lid's in the back. I can meet tomorrow morning."],
    ]),
  },
  {
    marketId: "wilmington-generator",
    at: ago(0.9),
    name: "Helen Marsh",
    phone: "(910) 619-4477",
    neighborhood: "St. James",
    zip: "28461",
    county: "brunswick",
    address: "2 Tournament Dr, St. James",
    source: "call",
    service: "22kW standby",
    notes: "Last outage 11 hours.",
    status: "new",
    screen: "unscreened",
    urgency: "week",
    screenNotes: "",
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, generators, desk."],
      ["0:05", "caller", "Helen in St. James. Last outage was eleven hours. I want a whole-house unit."],
      ["0:14", "agent", "Stay on. I'm pulling the screen — county, panel, and whether you want a site visit this week."],
    ]),
  },
  {
    marketId: "wilmington-dryer",
    at: ago(1.2),
    name: "Amy Lutz",
    phone: "(910) 710-3344",
    neighborhood: "Myrtle Grove",
    zip: "28409",
    county: "new-hanover",
    address: "812 Greenville Loop, Wilmington",
    source: "call",
    service: "Dryer vent cleaning",
    notes: "Burning smell. Dryer 90 min.",
    status: "new",
    screen: "hot",
    urgency: "today",
    screenNotes: "New Hanover. Burning smell, long run. Home after 2. Not a landlord mill.",
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, dryer vents, desk."],
      ["0:06", "caller", "Dryer takes 90 minutes and it smells like burning. Myrtle Grove."],
      ["0:14", "agent", "That's a fire risk. You in New Hanover?"],
      ["0:17", "caller", "Yes. I can be home after two."],
      ["0:22", "agent", "Screened. I'm handing a local tech, not a national list."],
    ]),
  },
  {
    marketId: "wilmington-garage",
    at: ago(2.0),
    name: "Nate Fowler",
    phone: "(910) 772-1560",
    neighborhood: "Myrtle Grove",
    zip: "28409",
    county: "new-hanover",
    address: "19 Salt Marsh Ln, Wilmington",
    source: "form",
    service: "Spring snap",
    notes: "Door off track. Salt rust.",
    status: "new",
    screen: "hot",
    urgency: "today",
    screenNotes: "New Hanover. Spring snapped, door off track. Cars trapped. Salt rust on cables.",
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, garage doors — calling on your form."],
      ["0:07", "caller", "Spring snapped. Door's off the track. Both cars are in."],
      ["0:14", "agent", "Anyone hurt? And is this Myrtle Grove / New Hanover?"],
      ["0:18", "caller", "Nobody hurt. Yes. Hardware is rusted to hell from the salt."],
    ]),
  },
  {
    marketId: "wilmington-septic",
    at: ago(10),
    name: "Ed Lowry",
    phone: "(910) 333-1182",
    neighborhood: "Porters Neck",
    zip: "28411",
    county: "new-hanover",
    address: "6 Creekstone Ct, Wilmington",
    source: "call",
    service: "Pumping",
    notes: "",
    status: "sold",
    screen: "hot",
    urgency: "today",
    screenNotes: "New Hanover. Routine pump, 5 years overdue. Handed Pell — FREE 1 of 2.",
    soldToBuyerId: "by-pell",
    soldPrice: 0,
    soldAt: ago(9.7),
    free: true,
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, septic, desk."],
      ["0:05", "caller", "Need a pump in Porters Neck. Last one was 2019."],
      ["0:12", "agent", "That's New Hanover. I'll screen and hand you to the owner."],
    ]),
  },
  {
    marketId: "wilmington-septic",
    at: ago(14),
    name: "Maya Chen",
    phone: "(910) 288-4410",
    neighborhood: "Carolina Beach",
    zip: "28428",
    county: "new-hanover",
    address: "210 Canal Dr, Carolina Beach",
    source: "form",
    service: "Lid locate",
    notes: "",
    status: "sold",
    screen: "warm",
    urgency: "week",
    screenNotes: "New Hanover. Lid locate for a sale. Handed Pell — FREE 2 of 2.",
    soldToBuyerId: "by-pell",
    soldPrice: 0,
    soldAt: ago(13.6),
    free: true,
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, septic, calling on your form."],
      ["0:06", "caller", "Can't find the lid. Carolina Beach. Selling next month."],
    ]),
  },
  {
    marketId: "wilmington-septic",
    at: ago(18),
    name: "Ron Ellis",
    phone: "(910) 555-0199",
    neighborhood: "Leland",
    zip: "28451",
    county: "brunswick",
    address: "90 Old Fayetteville Rd, Leland",
    source: "call",
    service: "Backup",
    notes: "",
    status: "sold",
    screen: "hot",
    urgency: "now",
    screenNotes: "Brunswick backup. Paid — Pell's free is gone.",
    soldToBuyerId: "by-pell",
    soldPrice: 50,
    soldAt: ago(17.8),
    free: false,
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, septic."],
      ["0:04", "caller", "Backup in Leland. Now."],
    ]),
  },
  {
    marketId: "wilmington-septic",
    at: ago(22),
    name: "Sue Pratt",
    phone: "(910) 671-3300",
    neighborhood: "Southport",
    zip: "28461",
    county: "brunswick",
    address: "14 Yacht Harbor Dr, Southport",
    source: "form",
    service: "Inspection",
    notes: "Realtor. Closing Monday.",
    status: "sold",
    screen: "hot",
    urgency: "week",
    screenNotes: "Brunswick. Realtor close Monday. Cape Pumping — FREE 1 of 2.",
    soldToBuyerId: "by-cape",
    soldPrice: 0,
    soldAt: ago(21.5),
    free: true,
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, septic, desk."],
      ["0:05", "caller", "Southport closing Monday. Need inspect plus pump."],
    ]),
  },
  {
    marketId: "wilmington-generator",
    at: ago(12),
    name: "Arthur Kim",
    phone: "(910) 909-3311",
    neighborhood: "Landfall",
    zip: "28405",
    county: "new-hanover",
    address: "3 Eagles Watch, Wilmington",
    source: "form",
    service: "24kW standby",
    notes: "",
    status: "sold",
    screen: "hot",
    urgency: "week",
    screenNotes: "New Hanover Landfall. 200A panel. Stormline — FREE 1 of 2.",
    soldToBuyerId: "by-storm",
    soldPrice: 0,
    soldAt: ago(11.4),
    free: true,
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, generators."],
      ["0:05", "caller", "Landfall. Want a 24kW. Panel is 200 amp."],
    ]),
  },
  {
    marketId: "wilmington-dryer",
    at: ago(9),
    name: "Pat Reese",
    phone: "(910) 441-2200",
    neighborhood: "Leland",
    zip: "28451",
    county: "brunswick",
    address: "55 Lanvale Forest, Leland",
    source: "call",
    service: "Vent cleaning",
    notes: "",
    status: "sold",
    screen: "hot",
    urgency: "today",
    screenNotes: "Brunswick. LintLock — still on free trial, this is uncharged demo of a paid-capable owner.",
    soldToBuyerId: "by-lint",
    soldPrice: 0,
    soldAt: ago(8.8),
    free: true,
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, dryer vents."],
      ["0:04", "caller", "Leland. Vent hasn't been done in four years."],
    ]),
  },
  {
    marketId: "wilmington-septic",
    at: ago(36),
    name: "Pam Ortiz",
    phone: "(910) 212-0094",
    neighborhood: "Leland",
    zip: "28451",
    county: "brunswick",
    address: "",
    source: "form",
    service: "Repair",
    notes: "Ghosted.",
    status: "dead",
    screen: "dead",
    urgency: "quote",
    screenNotes: "No answer on two follow-ups. Dead.",
    deadReason: "No answer on two follow-ups",
    conversation: turns([
      ["0:00", "agent", "Freedom Project Leads, septic, calling on your form."],
      ["0:08", "agent", "Second attempt. Voicemail."],
    ]),
  },
  {
    marketId: "wilmington-septic",
    at: ago(40),
    name: "Cal Dyer",
    phone: "(910) 441-2290",
    neighborhood: "Leland",
    zip: "28451",
    county: "brunswick",
    address: "118 Pine Needle Ct, Leland",
    source: "form",
    service: "Emergency backup",
    notes: "Same as Carla call.",
    status: "duplicate",
    screen: "dead",
    screenNotes: "Same household as Carla Dyer inbound.",
    conversation: [],
  },
];

export const SEED_LEADS: Lead[] = LEAD_SEEDS.map((lead, i) => ({
  ...lead,
  id: `ld-${String(i + 1).padStart(3, "0")}`,
}));

export function withRolledUpCounts(markets: Market[], buyers: Buyer[], leads: Lead[]) {
  const nextMarkets = markets.map((market) => {
    const mine = leads.filter((l) => l.marketId === market.id);
    const sold = mine.filter((l) => l.status === "sold");
    const revenue = sold.reduce((s, l) => s + (l.soldPrice ?? 0), 0);
    return {
      ...market,
      leadsThisMonth: mine.filter((l) => l.status !== "duplicate").length,
      soldThisMonth: sold.length,
      revenueThisMonth: revenue,
    };
  });
  const nextBuyers = buyers.map((b) => {
    const sold = leads.filter((l) => l.status === "sold" && l.soldToBuyerId === b.id);
    const freeUsed = sold.filter((l) => l.free).length;
    return {
      ...b,
      soldThisMonth: sold.length,
      spendThisMonth: sold.reduce((s, l) => s + (l.soldPrice ?? 0), 0),
      freeUsed,
      freeRemaining: b.hunt === "paying" ? 0 : Math.max(0, FREE_TRIAL - freeUsed),
    };
  });
  return { markets: nextMarkets, buyers: nextBuyers, leads };
}

const rolled = withRolledUpCounts(SEED_MARKETS, SEED_BUYERS, SEED_LEADS);
export const INITIAL_MARKETS = rolled.markets;
export const INITIAL_BUYERS = rolled.buyers;
export const INITIAL_LEADS = rolled.leads;

export function inferCounty(hood: string, market: Market): County {
  return inferCountyFromHood(hood, market.counties[0] ?? "new-hanover");
}
