/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsMarketIdRouteImport } from './routes/markets.$marketId'
import { Route as QueueIndexRouteImport } from './routes/queue.index'
import { Route as QueueLeadIdRouteImport } from './routes/queue.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/$marketId',
  path: '/$marketId',
  getParentRoute: () => MarketsRoute,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QueueRoute,
} as any)
const QueueLeadIdRoute = QueueLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => QueueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/buyers': typeof BuyersRoute
  '/leads': typeof LeadsRoute
  '/markets': typeof MarketsRouteWithChildren
  '/playbook': typeof PlaybookRoute
  '/queue': typeof QueueRouteWithChildren
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/queue/$leadId': typeof QueueLeadIdRoute
  '/markets/': typeof MarketsIndexRoute
  '/queue/': typeof QueueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/buyers': typeof BuyersRoute
  '/leads': typeof LeadsRoute
  '/playbook': typeof PlaybookRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/queue/$leadId': typeof QueueLeadIdRoute
  '/markets': typeof MarketsIndexRoute
  '/queue': typeof QueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/buyers': typeof BuyersRoute
  '/leads': typeof LeadsRoute
  '/markets': typeof MarketsRouteWithChildren
  '/playbook': typeof PlaybookRoute
  '/queue': typeof QueueRouteWithChildren
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/queue/$leadId': typeof QueueLeadIdRoute
  '/markets/': typeof MarketsIndexRoute
  '/queue/': typeof QueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/buyers'
    | '/leads'
    | '/markets'
    | '/playbook'
    | '/queue'
    | '/markets/$marketId'
    | '/queue/$leadId'
    | '/markets/'
    | '/queue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/buyers'
    | '/leads'
    | '/playbook'
    | '/markets/$marketId'
    | '/queue/$leadId'
    | '/markets'
    | '/queue'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/buyers'
    | '/leads'
    | '/markets'
    | '/playbook'
    | '/queue'
    | '/markets/$marketId'
    | '/queue/$leadId'
    | '/markets/'
    | '/queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  BuyersRoute: typeof BuyersRoute
  LeadsRoute: typeof LeadsRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  PlaybookRoute: typeof PlaybookRoute
  QueueRoute: typeof QueueRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/queue/': {
      id: '/queue/'
      path: '/'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof QueueRoute
    }
    '/queue/$leadId': {
      id: '/queue/$leadId'
      path: '/$leadId'
      fullPath: '/queue/$leadId'
      preLoaderRoute: typeof QueueLeadIdRouteImport
      parentRoute: typeof QueueRoute
    }
  }
}

interface MarketsRouteChildren {
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsMarketIdRoute: MarketsMarketIdRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

interface QueueRouteChildren {
  QueueLeadIdRoute: typeof QueueLeadIdRoute
  QueueIndexRoute: typeof QueueIndexRoute
}

const QueueRouteChildren: QueueRouteChildren = {
  QueueLeadIdRoute: QueueLeadIdRoute,
  QueueIndexRoute: QueueIndexRoute,
}

const QueueRouteWithChildren = QueueRoute._addFileChildren(QueueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  BuyersRoute: BuyersRoute,
  LeadsRoute: LeadsRoute,
  MarketsRoute: MarketsRouteWithChildren,
  PlaybookRoute: PlaybookRoute,
  QueueRoute: QueueRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
